import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: [
    {
      path: "../fonts/yekan/YekanBakh-Bold.woff",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-myfont",
});
const myFont2 = localFont({
  src: [
    {
      path: "../fonts/tanha/Tanha-FD.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-myfont2",
});
const vazirMatn = localFont({
  src: [
    {
      path: "../fonts/Vazirmatn/Vazirmatn-Black.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-vazirmatn",
});
const estedad = localFont({
  src: [
    {
      path: "../fonts/estedad/Estedad-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/estedad/Estedad-Medium.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-estedad",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} ${myFont.variable} ${myFont2.variable} ${vazirMatn.variable} ${estedad.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-estedad!">{children}</body>
    </html>
  );
}
